% summarises participantCompendium statistics

load participantList

% strmatch('RME', char(participant.initials))

fprintf('\n')
IH_NH=[participant.IH_NH];
disp (['number of participants = ' num2str(length([IH_NH]))])

age=[participant.age];
% disp (['average age = ' num2str(mean(age(~isnan(age))), '%3.1f') ])

idxImpaired= (IH_NH=='I');
idxNormal= (IH_NH=='N');
disp (['number of impaired /normal hearing = ' ...
    num2str(sum(idxImpaired)) ' / ' ...
    num2str(sum(idxNormal)) ])

gender=[participant.gender];
fprintf('\n')
disp (['number of impaired males /females = ' ...
    num2str(sum(gender(idxImpaired)=='M')) ' / ' ...
    num2str(sum(gender(idxImpaired)=='F')) ])
disp (['number of normal males/females = ' ...
    num2str(sum(gender(~idxImpaired)=='M')) ' / ' ...
    num2str(sum(gender(~idxImpaired)=='F')) ])

ageImpaired= age(idxImpaired);
ageNormal= age(idxNormal);
disp (['average age impaired/ normal = ' ...
    num2str(mean(ageImpaired(~isnan(ageImpaired))), '%3.1f')  ' (' ...
    num2str(std(ageImpaired(~isnan(ageImpaired))), '%3.1f')  ')' ...
    ' / ' ...
    num2str(mean(ageNormal(~isnan(ageNormal))), '%3.1f') ' (' ...
    num2str(std(ageNormal(~isnan(ageNormal))), '%3.1f') ' )' ...
    ])

tinnitus=[participant.tinnitus];
idxTinnitus=(tinnitus=='Y') & (IH_NH=='I');
idxNoTinnitus=(tinnitus=='N') & (IH_NH=='I');
idxTinnitusUnsure=~(tinnitus=='N') & ~(tinnitus=='Y') & (IH_NH=='I');
fprintf('\n')
disp (['impaired with tinnitus yes/no/not determined = ' ...
    num2str(sum(idxTinnitus)) ' / ' ...
    num2str(sum(idxNoTinnitus))  ' / ' ...
    num2str(sum(idxTinnitusUnsure))  ])

ear=char(participant(idxImpaired).ear);
idxLandR=strmatch('RL', ear);
idxLorR=[strmatch('L', ear,'exact');  strmatch('R', ear,'exact')];
disp (['Impaired: double ear / single ear  = ' ...
    num2str(length(idxLandR)) ' / ' ...
    num2str(length(idxLorR))  ])

ear=char(participant(idxNormal).ear);
idxLandR=strmatch('RL', ear);
idxLorR=[strmatch('L', ear,'exact');  strmatch('R', ear,'exact')];
disp (['Normal: double ear / single ear  = ' ...
    num2str(length(idxLandR)) ' / ' ...
    num2str(length(idxLorR))  ])
